"""
DO NOT EDIT - Auto-generated file
Generated by talon-pack v3.2.1

This file provides:
- Duplicate package detection
- Package version checking via rig_core_version() action
"""
import json
from pathlib import Path
from talon import Module, actions

_duplicate = False
try:
    actions.user.rig_core_version()
    _duplicate = True
except Exception:
    pass

if _duplicate:
    print("============================================================")
    print("DUPLICATE PACKAGE: talon-rig-core (user.rig_core)")
    print("")
    print("  talon-rig-core is already loaded from another location.")
    print("  Remove the duplicate so only one copy exists in talon/user.")
    print("============================================================")
    raise RuntimeError(
        "Duplicate package: talon-rig-core (user.rig_core) is already loaded."
    )

mod = Module()

_cached_version = None

def _get_version() -> tuple[int, int, int]:
    """
    Loads version from manifest.json. Cached after first successful load.
    To reload: restart Talon or save this file
    """
    global _cached_version
    if _cached_version is not None:
        return _cached_version

    try:
        with open(Path(__file__).parent / 'manifest.json', 'r', encoding='utf-8') as f:
            version = tuple(map(int, json.load(f)['version'].split('.')))
            _cached_version = version
            return version
    except Exception as e:
        print(f"ERROR: talon-rig-core failed to load version from manifest.json: {e}")
        return (0, 0, 0)

@mod.action_class
class Actions:
    def rig_core_version() -> tuple[int, int, int]:
        """
        Returns the package version as (major, minor, patch).

        Usage: actions.user.rig_core_version() >= (1, 2, 0)
        """
        return _get_version()
